using System.Collections.Frozen;
using System.Collections.Generic;

namespace TekkenFrameData.Watcher.Services.Framedata;

/// <summary>
/// Provides alias mappings for Tekken characters or moves.
/// </summary>
public static class Aliases
{
    public static readonly FrozenDictionary<string, string[]> CharacterNameAliases = new Dictionary<
        string,
        string[]
    >()
    {
        { "alisa", ["ali", "als"] },
        { "anna", ["ann", "annochka", "anya"] },
        //{ "armor_king", new string[] { "armorking", "amk", "ak", "armor king", "armor" } },
        { "asuka", ["asu"] },
        { "bryan", ["bry", "brayn"] },
        { "claudio", ["cld", "cla"] },
        { "clive", ["rosfield", "clivers", "cliverosfield", "cliventura"] },
        { "devil jin", ["dj", "deviljin", "dvj", "devil jin", "devil"] },
        { "dragunov", ["drag", "sergei", "dragu"] },
        { "eddy", ["edd", "ed"] },
        //{ "eliza", new string[] { "elz" } },
        { "feng", ["fen"] },
        { "hwoarang", ["hwo"] },
        { "jack-8", ["j8", "jack 8", "jack", "jack7", "j7"] },
        { "jin", ["jim"] },
        { "jun", [""] },
        //{ "julia", new string[] { "jul" } },
        { "kazuya", ["kaz", "kazze", "masku"] },
        { "king", ["kin"] },
        { "kuma", ["karhu", "bear"] },
        { "panda", [] },
        { "lars", ["lar"] },
        { "law", ["marshall"] },
        { "lee", ["violet"] },
        //{ "lei", new string[] {""}},
        { "leo", [""] },
        { "lili", ["lil"] },
        { "lidia", ["lid", "lidl", "lydia", "lydya"] },
        //{ "marduk", new string[] { "mdk", "mar", "duk", "craig" } },
        { "raven", ["masterraven", "mraven", "maven", "mrv", "mr", "master raven", "master"] },
        { "nina", ["nin"] },
        { "paul", [""] },
        { "shaheen", ["sha"] },
        { "steve", ["stv", "ste", "fox"] },
        { "yoshimitsu", ["yoshi", "manji", "yos"] },
        { "xiaoyu", ["xiao", "ling"] },
        { "zafina", ["zaffy", "zaf"] },
        { "fahkumram", new[] { "fah", "fahkum", "fahk", "fak" } },
        { "leroy", ["ler"] },
        //{"ganryu", new string[]{"gan", "ganny"}},
        //{"kunimitsu", new string[]{"kun", "kuni"}},
        { "azucena", ["azu"] },
        { "victor", ["vic", "victorian", "viktoriues"] },
        { "reina", ["rheina"] },
        { "heihachi", ["hei", "hachi"] },
        //{ "mokujin", ["mokujin", "mokuj"] },
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<string, string> MoveInputReplacer = new Dictionary<
        string,
        string
    >()
    {
        { "cd+", "fnddf" },
        { "cd", "fnddf" },
        { "wr+", "fff" },
        { "wr", "fff" },
        { "hcb", "fdfddbb" },
        { "hcf", "bdbddff" },
        { "dp+", "fddf" },
        { "dp", "fddf" },
        { " ", "" },
        { ",", "" },
        { "/", "" },
        { "d+", "d" },
        { "f+", "f" },
        { "u+", "u" },
        { "b+", "b" },
        { "n+", "n" },
        { "ws+", "ws" },
        { "fc+", "fc" },
        //{"cd+", "cd"},
        //{"wr+", "wr"},
        { "ra+", "ra" },
        { "rd+", "rd" },
        { "ss+", "ss" },
        { "(", "" },
        { ")", "" },
        { "*+", "*" },
        { "hold", "*" },
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<string, string> Stances = new Dictionary<
        string,
        string
    >()
    {
        { "bkp", "Backup" },
        { "sbt", "Boot" },
        { "dbt", "Dual Boot" },
        { "des", "Destructive Form" },
        { "nwg", "Naniwa Gusto" },
        { "lib", "Libertador" },
        { "sls", "Slither step" },
        { "swa", "Sway" },
        { "sne", "Snake eyes" },
        { "stb", "Starburst" },
        { "fly", "Fly" },
        { "mcr", "Mourning crow" },
        { "snk", "Sneak" },
        { "hsp", "Bananeira" },
        { "rlx", "Negativa" },
        { "md1", "Mandinga 1" },
        { "md2", "Mandinga 2" },
        { "knp", "Deceptive step" },
        { "stc", "Shiting Clouds" },
        { "rff", "Right stance" },
        { "lfs", "Left flamingo stance" },
        { "rfs", "Right flamingo stance" },
        { "gmc", "Gamma Charge" },
        { "gmh", "Gamma Howl" },
        { "sit", "Sitdown" },
        { "zen", "Zenshin" },
        { "gen", "Genjitsu" },
        { "izu", "Izumo" },
        { "mia", "Miare" },
        { "dvk", "Devil form" },
        { "jgr", "Jaguar Run" },
        { "jgs", "Jaguar step" },
        { "hbs", "Hunting bear" },
        { "rol", "Roll" },
        { "den", "Dynamic entry" },
        { "sen", "Silent entry / Sentai" },
        { "len", "Limited entry" },
        { "dss", "Dragon stance" },
        { "hms", "Hitman" },
        { "ms", "Mist step" },
        { "knk", "Jin Ji Du Li" },
        { "bok", "Fo Bu" },
        { "hrm", "Hermit" },
        { "dew", "Dew glide" },
        { "rab", "Feisty rabbit" },
        { "cs", "Comorant step" },
        { "dpd", "Deep Dive" },
        { "szn", "Soulzone" },
        { "uns", "Unsoku" },
        { "wds", "Wind step" },
        { "wgs", "Wind God Step" },
        { "wra", "Heavens wrath" },
        { "dck", "Duck" },
        { "exd", "Ducking In" },
        { "flk", "Flicker" },
        { "lnh", "Lionheart" },
        { "lwv", "ducking left" },
        { "rwv", "ducking right" },
        { "pab", "Peekaboo" },
        { "swy", "Swaying" },
        { "tfa", "Two faced" },
        { "iai", "Iai stance" },
        { "prf", "Perfumer" },
        { "aop", "Phoenix" },
        { "hyp", "Hypnotist" },
        { "dgf", "Dragonfly" },
        { "fle", "Flea" },
        { "ind", "Indian stance" },
        { "med", "Meditation" },
        { "kin", "KINCHO" },
        { "nss", "no sword stance" },
        { "bds", "Bad stomach" },
        { "mnt", "Mantis" },
        { "scr", "Scarecrow" },
        { "trt", "Tarantula" },
        { "cat", "Cat Stance" },
        { "wlf", "Stalking Wolf" },
        { "hae", "Heaven and Earth" },
        { "hrs", "Horse Stance" },
        { "war", "Warrior Instinct" },
        { "fuj", "Fujin" },
        { "rai", "Raijin" },
        { "gar", "Updraft" },
        { "wol", "Wings of Light" },
        { "phx", "Phoenix Shift" },
        { "tom", "Pleasure Time" },
        { "cjm", "Chaos Judgement" },
        { "ham", "Hammer Chance" },
    }.ToFrozenDictionary();
}
