using System.Collections.Generic;

namespace TekkenFrameData.Watcher.Services.Framedata;

public class Aliases
{
    public static readonly Dictionary<string, string[]> CharacterNameAliases = new()
    {
        { "alisa", new[] { "ali", "als" } },
        //{ "anna", new string[] {""}},
        //{ "armor_king", new string[] { "armorking", "amk", "ak", "armor king", "armor" } },
        { "asuka", new[] { "asu" } },
        { "bryan", new[] { "bry" } },
        { "claudio", new[] { "cld", "cla" } },
        { "devil jin", new[] { "dj", "deviljin", "dvj", "devil jin", "devil" } },
        { "dragunov", new[] { "drag", "sergei", "dragu" } },
        { "eddy", new[] { "edd", "ed" } },
        //{ "eliza", new string[] { "elz" } },
        { "feng", new[] { "fen" } },
        { "hwoarang", new[] { "hwo" } },
        { "jack 8", new[] { "j8", "jack-8", "jack", "jack7", "j7" } },
        { "jin", new[] { "jim" } },
        { "jun", new[] { "" } },
        //{ "julia", new string[] { "jul" } },
        { "kazuya", new[] { "kaz", "kazze", "masku" } },
        { "king", new[] { "kin" } },
        { "kuma", new[] { "karhu", "bear" } },
        { "panda", [] },
        { "lars", new[] { "lar" } },
        { "law", new[] { "marshall" } },
        { "lee", new[] { "violet" } },
        //{ "lei", new string[] {""}},
        { "leo", new[] { "" } },
        { "lili", new[] { "lil" } },
        { "lidia", new string[] { "lid", "lidl", "lydia", "lydya", "lydyaa" } },
        //{ "marduk", new string[] { "mdk", "mar", "duk", "craig" } },
        { "raven", new[] { "masterraven", "mraven", "maven", "mrv", "mr", "master raven", "master" } },
        { "nina", new[] { "nin" } },
        { "paul", new[] { "" } },
        { "shaheen", new[] { "sha" } },
        { "steve", new[] { "stv", "ste", "fox" } },
        { "yoshimitsu", new[] { "yoshi", "manji", "yos" } },
        { "xiaoyu", new[] { "xiao", "ling" } },
        { "zafina", new[] { "zaffy", "zaf" } },
        //{"fahkumram", new string[]{"fah", "fahkum", "fahk", "fak"}},
        { "leroy", new[] { "ler" } },
        //{"ganryu", new string[]{"gan", "ganny"}},
        //{"kunimitsu", new string[]{"kun", "kuni"}},
        { "azucena", new[] { "azu" } },
        { "victor", new[] { "vic", "victorian", "viktoriues" } },
        { "reina", new[] { "rheina" } },
        { "mokujin", new []{ "mokujin" }}
    };

    public static readonly Dictionary<string, string> MoveInputReplacer = new()
    {
        { "cd+", "fnddf" },
        { "cd", "fnddf" },
        { "wr+", "fff" },
        { "wr", "fff" },
        { "hcb", "fdfddbb" },
        { "hcf", "bdbddff" },
        { "dp+", "fddf" },
        { "dp", "fddf" },
        { " ", "" },
        { ",", "" },
        { "/", "" },
        { "d+", "d" },
        { "f+", "f" },
        { "u+", "u" },
        { "b+", "b" },
        { "n+", "n" },
        { "ws+", "ws" },
        { "fc+", "fc" },
        //{"cd+", "cd"},
        //{"wr+", "wr"},
        { "ra+", "ra" },
        { "rd+", "rd" },
        { "ss+", "ss" },
        { "(", "" },
        { ")", "" },
        { "*+", "*" },
        { "hold", "*" }
    };
}