version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: only_watcher_tekken_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tekken_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5552:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

  watcher:
    image: tekken_frame_data.watcher:dev
    build:
      context: .
      dockerfile: TekkenFrameData.Backend/TekkenFrameData.Watcher/Dockerfile
    container_name: only_watcher_tekken_watcher
    command: ["dotnet", "ef", "database update"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tekken_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    extra_hosts:
      - "irc.chat.twitch.tv:127.0.0.1"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    links:
      - "db:db"
    ports:
      - "7080:8080"
      - "7081:8081"
    networks:
      - default


volumes:
  postgres_data:
    
networks:
  default:
    driver: bridge