version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: tekken_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tekken_db
    volumes:
      - postgres_data:/var/lib/postgresql@latest/data
    ports:
      - "5432:5432"
    networks:
      - tekken_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: tekken_frame_data.migrations:latest
    build:
      context: ./
      dockerfile: ./TekkenFrameData.Backend/TekkenFrameData.Cli/Dockerfile
    container_name: tekken_migrations
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tekken_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - tekken_network

  scraper:
    image: tekken_frame_data.scraper:latest
    build:
      context: ./TekkenFrameData.Scraper
      dockerfile: Dockerfile
    container_name: tekken_scraper
    depends_on:
      migrations:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tekken_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - tekken_network

  service:
    image: tekken_frame_data.service:latest
    build:
      context: ./
      dockerfile: TekkenFrameData.Backend/TekkenFrameData.Service/Dockerfile
    container_name: tekken_service
    depends_on:
      scraper:
        condition: service_started
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - tekken_network

  watcher:
    image: tekken_frame_data.watcher:latest
    build:
      context: ./
      dockerfile: TekkenFrameData.Backend/TekkenFrameData.Watcher/Dockerfile
    container_name: tekken_watcher
    depends_on:
      frontend:
        condition: service_started
    ports:
      - "7080:8080"
      - "7081:8081"
    networks:
      - tekken_network

  frontend:
    image: tekken_frame_data.frontend:latest
    build:
      context: ./TekkenFrameData.Frontend
      dockerfile: Dockerfile
    container_name: tekken_frontend
    depends_on:
      service:
        condition: service_started
    ports:
      - "6080:5173"
    networks:
      - tekken_network

volumes:
  postgres_data:

networks:
  tekken_network:
    driver: bridge
    name: "TekkenNetwork"
    internal: true
  