namespace tekkenfd.Services.Framedata;

public class Aliases
{
    public static readonly Dictionary<string, string[]> CharacterNameAliases = new()
    {
        { "alisa", new[] { "ali", "als" } },
        //{ "anna", new string[] {""}},
        //{ "armor_king", new string[] { "armorking", "amk", "ak", "armor king", "armor" } },
        { "asuka", new[] { "asu" } },
        { "bryan", new[] { "bry" } },
        { "claudio", new[] { "cld", "cla" } },
        { "devil jin", new[] { "dj", "deviljin", "dvj", "devil jin", "devil" } },
        { "dragunov", new[] { "drag", "sergei", "dragu" } },
        { "eddy", new[] { "edd", "ed" } },
        //{ "eliza", new string[] { "elz" } },
        { "feng", new[] { "fen" } },
        { "hwoarang", new[] { "hwo" } },
        { "jack 8", new[] { "j8", "jack-8", "jack", "jack7", "j7" } },
        { "jin", new[] { "jim" } },
        { "jun", new[] { "" } },
        //{ "julia", new string[] { "jul" } },
        { "kazuya", new[] { "kaz", "kazze", "masku" } },
        { "king", new[] { "kin" } },
        { "kuma", new[] { "karhu", "bear" } },
        { "panda", new string[] { } },
        { "lars", new[] { "lar" } },
        { "law", new[] { "marshall" } },
        { "lee", new[] { "violet" } },
        //{ "lei", new string[] {""}},
        { "leo", new[] { "" } },
        { "lili", new[] { "lil" } },
        { "lidia", new string[] { "lid", "lidl", "lydia", "lydya", "lydyaa" } },
        //{ "marduk", new string[] { "mdk", "mar", "duk", "craig" } },
        { "raven", new[] { "masterraven", "mraven", "maven", "mrv", "mr", "master raven", "master" } },
        { "nina", new[] { "nin" } },
        { "paul", new[] { "" } },
        { "shaheen", new[] { "sha" } },
        { "steve", new[] { "stv", "ste", "fox" } },
        { "yoshimitsu", new[] { "yoshi", "manji", "yos" } },
        { "xiaoyu", new[] { "xiao", "ling" } },
        { "zafina", new[] { "zaffy", "zaf" } },
        //{"fahkumram", new string[]{"fah", "fahkum", "fahk", "fak"}},
        { "leroy", new[] { "ler" } },
        //{"ganryu", new string[]{"gan", "ganny"}},
        //{"kunimitsu", new string[]{"kun", "kuni"}},
        { "azucena", new[] { "azu" } },
        { "victor", new[] { "vic", "victorian", "viktoriues" } },
        { "reina", new[] { "rheina" } }
    };

    public static readonly Dictionary<string, string> MoveInputReplacer = new()
    {
        { "cd+", "fnddf" },
        { "cd", "fnddf" },
        { "wr+", "fff" },
        { "wr", "fff" },
        { "hcb", "fdfddbb" },
        { "hcf", "bdbddff" },
        { "dp+", "fddf" },
        { "dp", "fddf" },
        { " ", "" },
        { ",", "" },
        { "/", "" },
        { "d+", "d" },
        { "f+", "f" },
        { "u+", "u" },
        { "b+", "b" },
        { "n+", "n" },
        { "ws+", "ws" },
        { "fc+", "fc" },
        //{"cd+", "cd"},
        //{"wr+", "wr"},
        { "ra+", "ra" },
        { "rd+", "rd" },
        { "ss+", "ss" },
        { "(", "" },
        { ")", "" },
        { "*+", "*" },
        { "hold", "*" }
    };

    public static Dictionary<string, string> Stances = new()
    {
        { "bkp", "Backup" },
        { "sbt", "Boot" },
        { "dbt", "Dual Boot" },
        { "des", "Destructive Form" },
        { "nwg", "Naniwa Gusto" },
        { "lib", "Libertador" },
        { "sls", "Slither step" },
        { "swa", "Sway" },
        { "sne", "Snake eyes" },
        { "stb", "Starburst" },
        { "fly", "Fly" },
        { "mcr", "Mourning crow" },
        { "snk", "Sneak" },
        { "hsp", "Bananeira" },
        { "rlx", "Negativa" },
        { "md1", "Mandinga 1" },
        { "md2", "Mandinga 2" },
        { "knp", "Deceptive step" },
        { "stc", "Shiting Clouds" },
        { "rff", "Right stance" },
        { "lfs", "Left flamingo stance" },
        { "rfs", "Right flamingo stance" },
        { "gmc", "Gamma Charge" },
        { "gmh", "Gamma Howl" },
        { "sit", "Sitdown" },
        { "zen", "Zenshin" },
        { "gen", "Genjitsu" },
        { "izu", "Izumo" },
        { "mia", "Miare" },
        { "dvk", "Devil form" },
        { "jgr", "Jaguar Run" },
        { "jgs", "Jaguar step" },
        { "hbs", "Hunting bear" },
        { "rol", "Roll" },
        { "den", "Dynamic entry" },
        { "sen", "Silent entry / Sentai" },
        { "len", "Limited entry" },
        { "dss", "Dragon stance" },
        { "hms", "Hitman" },
        { "ms", "Mist step" },
        { "knk", "Jin Ji Du Li" },
        { "bok", "Fo Bu" },
        { "hrm", "Hermit" },
        { "dew", "Dew glide" },
        { "rab", "Feisty rabbit" },
        { "cs", "Comorant step" },
        { "dpd", "Deep Dive" },
        { "szn", "Soulzone" },
        { "uns", "Unsoku" },
        { "wds", "Wind step" },
        { "wgs", "Wind God Step" },
        { "wra", "Heavens wrath" },
        { "dck", "Duck" },
        { "exd", "Ducking In" },
        { "flk", "Flicker" },
        { "lnh", "Lionheart" },
        { "lwv", "ducking left" },
        { "rwv", "ducking right" },
        { "pab", "Peekaboo" },
        { "swy", "Swaying" },
        { "tfa", "Two faced" },
        { "iai", "Iai stance" },
        { "prf", "Perfumer" },
        { "aop", "Phoenix" },
        { "hyp", "Hypnotist" },
        { "dgf", "Dragonfly" },
        { "fle", "Flea" },
        { "ind", "Indian stance" },
        { "med", "Meditation" },
        { "kin", "KINCHO" },
        { "nss", "no sword stance" },
        { "bds", "Bad stomach" },
        { "mnt", "Mantis" },
        { "scr", "Scarecrow" },
        { "trt", "Tarantula" },
        { "cat", "Cat Stance"},
        { "wlf", "Stalking Wolf"},
        { "hae", "Heaven and Earth"},
        { "hrs", "Horse Stance"}
    };
}