// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using AppDbContext = TekkenFrameData.Library.DB.AppDbContext;

#nullable disable

namespace TekkenFrameData.Cli.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250124200920_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TekkenFrameData.Library.Models.Configuration.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("TekkenFrameData.Library.Models.FrameData.TekkenCharacter", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkToImage")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("TekkenCharacters");
                });

            modelBuilder.Entity("TekkenFrameData.Library.Models.FrameData.TekkenMove", b =>
                {
                    b.Property<string>("CharacterName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Command")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("BlockFrame")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CounterHitFrame")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Damage")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("HeatBurst")
                        .HasColumnType("boolean");

                    b.Property<bool>("HeatEngage")
                        .HasColumnType("boolean");

                    b.Property<bool>("HeatSmash")
                        .HasColumnType("boolean");

                    b.Property<string>("HitFrame")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HitLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Homing")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUserChanged")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("PowerCrush")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresHeat")
                        .HasColumnType("boolean");

                    b.Property<string>("StanceCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("StanceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StartUpFrame")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("Throw")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tornado")
                        .HasColumnType("boolean");

                    b.HasKey("CharacterName", "Command");

                    b.ToTable("TekkenMoves");
                });

            modelBuilder.Entity("TekkenFrameData.Library.Models.FrameData.TekkenMove", b =>
                {
                    b.HasOne("TekkenFrameData.Library.Models.FrameData.TekkenCharacter", "Character")
                        .WithMany("Movelist")
                        .HasForeignKey("CharacterName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TekkenFrameData.Library.Models.FrameData.TekkenCharacter", b =>
                {
                    b.Navigation("Movelist");
                });
#pragma warning restore 612, 618
        }
    }
}
