name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Получение кода из репозитория
    - uses: actions/checkout@v4

    # Шаг 2: Установка Docker и Docker Compose
    - name: Set up Docker
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Шаг 3: Сборка Docker-образов
    - name: Build Docker images
      run: |
        docker-compose -f docker-compose.short.yml build

    # Шаг 4: Запуск контейнеров с помощью docker-compose
    - name: Run Docker containers
      run: |
        docker-compose -f docker-compose.short.yml up -d

    # Шаг 5: Проверка состояния контейнеров
    - name: Check container status
      run: |
        docker ps -a
